apiVersion: v1
kind: Pod
metadata:                                 
  name: Hello-pod
  namespace: roboshop
spec:
  containers:
  - name: pod-1
    image: nginx
    ports:
    - containerPort: 80
          

