apiVersion: v1
kind: Pod
metadata:
  name: multi-container
  namespace: roboshop
spec:
  containers:
  - name: container-1
    image: nginx
    ports:
    - containerPort: 80
  - name: container-2
    image: dockerhub2009/mongodb:v1
    command: ["sleep","300"]    

