apiVersion: v1
kind: Pod
metadata:
  name: multi-containers
  namespace: roboshop
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80
  - name: almalinux
    image: almalinux:8
    command: ["sleep","300"]    