apiVersion: v1
kind: Pod
metadata:
  name: config-pod
spec:
  containers:
  - name: config-container
    image: nginx
    ports:
    - containerPort: 80
    env:
    - name: course
      valueFrom:
        configMapKeyRef:
          name: devops-config
          key: course
    - name: trainer
      valueFrom:
        configMapKeyRef:
          name: devops-config
          key: trainer     
---  
apiVersion: v1
kind: Pod
metadata:
  name: config-pod-1
spec:
  containers:
  - name: config-container-1
    image: nginx
    ports:
    - containerPort: 80
    envFrom:
    - configMapKeyRef:
        name: devops-config
   